### ISSUE TITLE
fix: Update templates for hemmer-provider-sdk 0.3 compatibility

### ISSUE THREAD

**Issue by turner-hemmer** [hemmer-io/hemmer-provider-generator#107]
## Summary

Integration testing (#91) has revealed that our templates generate code that doesn't compile with hemmer-provider-sdk 0.3. The templates were written for an older SDK version and need to be updated.

## Errors Found

When running `cargo check` on generated providers, we get these compilation errors:

### 1. Wrong trait method signatures

**Current (wrong)**:
```rust
async fn configure(&self, config: serde_json::Value) -> Result<Vec<tonic::Status>, tonic::Status>
```

**Expected by SDK 0.3**:
```rust
async fn validate_config(&self, config: serde_json::Value) -> Result<Vec<Diagnostic>, ProviderError>
```

### 2. Wrong error types

Templates use `tonic::Status` but SDK 0.3 uses `ProviderError` throughout.

### 3. Wrong parameter counts

**Current (wrong)**:
```rust
async fn create(&self, resource_type: &str, planned_state: serde_json::Value, _config: serde_json::Value) -> Result<serde_json::Value, tonic::Status>
```

**Expected by SDK 0.3**:
```rust
async fn create(&self, resource_type: &str, planned_state: serde_json::Value) -> Result<serde_json::Value, ProviderError>
```

The SDK removed the `_config` parameter from CRUD methods.

### 4. Missing imports

Templates don't import `hemmer_provider_sdk::schema::Diagnostic` which is needed for `validate_config`.

## Files to Update

- `crates/generator/templates/lib.rs.tera` - Single-service provider
- `crates/generator/templates/unified_lib.rs.tera` - Multi-service provider

## Specific Changes Needed

1. Rename `configure` method to `validate_config`
2. Change return type from `Result<Vec<tonic::Status>, tonic::Status>` to `Result<Vec<Diagnostic>, ProviderError>`
3. Add import: `use hemmer_provider_sdk::schema::Diagnostic;`
4. Update all CRUD method signatures to use `ProviderError` instead of `tonic::Status`
5. Remove `_config` parameter from `create`, `read`, `update`, `delete` methods
6. Update error handling throughout to return `ProviderError` variants

## Context

This issue was discovered by the first integration test in #91, which runs `cargo check` on generated code. The integration test is working as intended - it caught that our templates are out of sync with the SDK!

## Related Issues

- #91 - Integration testing (parent issue)
- #80 - Added SDK 0.2 support (templates need to be updated for 0.3)

## Labels

`bug`, `generator`, `grpc`
